import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv('Iris.csv')
df.head()
df.shape
df.info()
df.describe()
df.isnull().sum()
data = df.drop_duplicates(subset ="Species",)
print(data)
df.value_counts("Species")
sns.countplot(x='Species', data=df, )
plt.show()
sns.scatterplot(x='SepalLengthCm', y='SepalWidthCm',hue='Species', data=df, )
plt.legend(bbox_to_anchor=(1, 1), loc=2)
plt.show()
sns.scatterplot(x='PetalLengthCm', y='PetalWidthCm',hue='Species', data=df, )
plt.legend(bbox_to_anchor=(1, 1), loc=2)
plt.show()
sns.pairplot(df.drop(['Id'], axis = 1),hue='Species', height=2)
fig, axes = plt.subplots(2, 2, figsize=(10,10))
axes[0,0].set_title("Sepal Length")
axes[0,0].hist(df['SepalLengthCm'], bins=7)
axes[0,1].set_title("Sepal Width")
axes[0,1].hist(df['SepalWidthCm'], bins=5);
axes[1,0].set_title("Petal Length")
axes[1,0].hist(df['PetalLengthCm'], bins=6);
axes[1,1].set_title("Petal Width")
axes[1,1].hist(df['PetalWidthCm'], bins=6);
plot = sns.FacetGrid(df, hue="Species")
plot.map(sns.distplot, "SepalLengthCm").add_legend()
plot = sns.FacetGrid(df, hue="Species")
plot.map(sns.distplot, "SepalWidthCm").add_legend()
plot = sns.FacetGrid(df, hue="Species")
plot.map(sns.distplot, "PetalLengthCm").add_legend()
plot = sns.FacetGrid(df, hue="Species")
plot.map(sns.distplot, "PetalWidthCm").add_legend()
plt.show()
data.select_dtypes(include=['number']).corr(method='pearson')
sns.heatmap(df.select_dtypes(include=['number']).corr(method='pearson').drop( ['Id'], axis=1).drop(['Id'], axis=0), annot = True); 
plt.show()
def graph(y):
    sns.boxplot(x="Species", y=y, data=df)
plt.figure(figsize=(10,10))
plt.subplot(221)
graph('SepalLengthCm')
plt.subplot(222)
graph('SepalWidthCm')
plt.subplot(223)
graph('PetalLengthCm')
plt.subplot(224)
graph('PetalWidthCm')
plt.show()

